-- Import IEEE library
library IEEE;

-- Use STD_LOGIC data type
use IEEE.STD_LOGIC_1164.ALL;


-- Entity declaration
-- Defines the inputs and outputs of the D Latch
entity d_latch is

    Port (
        D      : in  STD_LOGIC;   -- Data input
        ENABLE : in  STD_LOGIC;   -- Enable input
        Q      : out STD_LOGIC;   -- Main output
        Q_n    : out STD_LOGIC    -- Complement output
    );

end d_latch;


-- Architecture declaration
-- Structural modeling is used
architecture Structural of d_latch is

    -- Declare the NOT gate component
    component not_gate
        Port (
            A : in  STD_LOGIC;
            Y : out STD_LOGIC
        );
    end component;


    -- Declare the NAND gate component
    component nand_gate
        Port (
            A : in  STD_LOGIC;
            B : in  STD_LOGIC;
            Y : out STD_LOGIC
        );
    end component;


    -- Declare the SR Latch component
    component sr_latch
        Port (
            S   : in  STD_LOGIC;
            R   : in  STD_LOGIC;
            Q   : out STD_LOGIC;
            Q_n : out STD_LOGIC
        );
    end component;


    -- Internal signals
    signal D_n : STD_LOGIC;   -- NOT of D
    signal S_i : STD_LOGIC;   -- Set signal
    signal R_i : STD_LOGIC;   -- Reset signal

begin

    -- NOT gate
    -- Creates the complement of D
    -- D_n = NOT D
    U1: not_gate
        port map (
            A => D,
            Y => D_n
        );


    -- NAND gate for Set signal
    -- S = NOT(D_n AND ENABLE)
    U2: nand_gate
        port map (
            A => D_n,
            B => ENABLE,
            Y => S_i
        );


    -- NAND gate for Reset signal
    -- R = NOT(D AND ENABLE)
    U3: nand_gate
        port map (
            A => D,
            B => ENABLE,
            Y => R_i
        );


    -- SR Latch
    -- Stores the data generated by the two NAND gates
    U4: sr_latch
        port map (
            S   => S_i,
            R   => R_i,
            Q   => Q,
            Q_n => Q_n
        );

end Structural;
